# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import faceRecognition_pb2 as protos_dot_faceRecognition__pb2


class FaceRecognitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getFaceEmbedding = channel.unary_unary(
                '/faceRecognition.FaceRecognition/getFaceEmbedding',
                request_serializer=protos_dot_faceRecognition__pb2.ImageRequest.SerializeToString,
                response_deserializer=protos_dot_faceRecognition__pb2.EmbeddingResponse.FromString,
                )
        self.getFaceEmbeddings = channel.unary_unary(
                '/faceRecognition.FaceRecognition/getFaceEmbeddings',
                request_serializer=protos_dot_faceRecognition__pb2.MultipleImageRequest.SerializeToString,
                response_deserializer=protos_dot_faceRecognition__pb2.MultipleEmbeddingResponse.FromString,
                )


class FaceRecognitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getFaceEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFaceEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getFaceEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.getFaceEmbedding,
                    request_deserializer=protos_dot_faceRecognition__pb2.ImageRequest.FromString,
                    response_serializer=protos_dot_faceRecognition__pb2.EmbeddingResponse.SerializeToString,
            ),
            'getFaceEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.getFaceEmbeddings,
                    request_deserializer=protos_dot_faceRecognition__pb2.MultipleImageRequest.FromString,
                    response_serializer=protos_dot_faceRecognition__pb2.MultipleEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faceRecognition.FaceRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getFaceEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/faceRecognition.FaceRecognition/getFaceEmbedding',
            protos_dot_faceRecognition__pb2.ImageRequest.SerializeToString,
            protos_dot_faceRecognition__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFaceEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/faceRecognition.FaceRecognition/getFaceEmbeddings',
            protos_dot_faceRecognition__pb2.MultipleImageRequest.SerializeToString,
            protos_dot_faceRecognition__pb2.MultipleEmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
